ApiConfig:
  ServePort: 0.0.0.0:4000
  RunMode: "debug"
  DBDriver: postgres
  DBSource: postgresql://postgres:abc123@localhost:5432/db_movie?sslmode=disable
  PageSize: 10
  MaxPageSize: 100

WebConfig:
  ServePort: 0.0.0.0:5000
  RunMode: "debug"
  DBDriver: postgres
  DBSource: postgresql://postgres:abc123@localhost:5432/db_movie?sslmode=disable
  PageSize: 10
  MaxPageSize: 100


