// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type Booking struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	ShowID     int64     `json:"show_id"`
	SeatNumber string    `json:"seat_number"`
	CreatedAt  time.Time `json:"created_at"`
	Status     int32     `json:"status"`
}

type Cinema struct {
	ID               int64  `json:"id"`
	CityID           int64  `json:"city_id"`
	Name             string `json:"name"`
	Lat              string `json:"lat"`
	Long             string `json:"long"`
	TotalCinemaHalls int32  `json:"total_cinema_halls"`
}

type CinemaHall struct {
	ID         int64  `json:"id"`
	CinemaID   int64  `json:"cinema_id"`
	Name       string `json:"name"`
	TotalSeats int32  `json:"total_seats"`
}

type CinemaSeat struct {
	ID int64 `json:"id"`
	// 可用/损坏/闲置
	Type         int32 `json:"type"`
	CinemaHallID int64 `json:"cinema_hall_id"`
	// 位置编号，如（1排2座）
	SeatNumber string `json:"seat_number"`
}

type City struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Lat  string `json:"lat"`
	Long string `json:"long"`
}

type Movie struct {
	ID int64 `json:"id"`
	// 电影名
	Title string `json:"title"`
	// 发布时间
	ReleaseAt time.Time `json:"release_at"`
	// 封面
	CoverUrl string `json:"cover_url"`
	// 时长
	Duration sql.NullTime `json:"duration"`
	// 语言
	Language sql.NullString `json:"language"`
	// 风格/类型
	Genre sql.NullString `json:"genre"`
	// 评分
	Rating sql.NullString `json:"rating"`
	// 导演
	Director sql.NullString `json:"director"`
	// 剧情
	Desc sql.NullString `json:"desc"`
	// 0:即将上映｜1:正在热映
	Status int32 `json:"status"`
	// 主演明星
	Star sql.NullString `json:"star"`
	// 想看人数
	WishCount sql.NullInt32 `json:"wish_count"`
}

type Oauth struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// 第三方登陆类型wechat\qq\weibo等
	OauthType string `json:"oauth_type"`
	// 第三方用户唯一标识
	OauthID string `json:"oauth_id"`
	// 腾讯体系unionid
	Unionid sql.NullString `json:"unionid"`
	// 登录凭证/access_token
	Credential sql.NullString `json:"credential"`
}

type Payment struct {
	ID        int64     `json:"id"`
	BookingID int64     `json:"booking_id"`
	Amount    string    `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Show struct {
	ID           int64     `json:"id"`
	Date         time.Time `json:"date"`
	StartTime    time.Time `json:"start_time"`
	EndTime      time.Time `json:"end_time"`
	CinemaHallID int64     `json:"cinema_hall_id"`
	MovieID      int64     `json:"movie_id"`
}

type ShowSeat struct {
	ID           int64  `json:"id"`
	CinemaSeatID int64  `json:"cinema_seat_id"`
	ShowID       int64  `json:"show_id"`
	BookingID    int64  `json:"booking_id"`
	Status       int32  `json:"status"`
	Price        string `json:"price"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Password  sql.NullString `json:"password"`
	Phone     sql.NullString `json:"phone"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
