// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error)
	CreateCinemaHall(ctx context.Context, arg CreateCinemaHallParams) (CinemaHall, error)
	CreateCinemaSeat(ctx context.Context, arg CreateCinemaSeatParams) (CinemaSeat, error)
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateOauths(ctx context.Context, arg CreateOauthsParams) (Oauth, error)
	CreateShow(ctx context.Context, arg CreateShowParams) (Show, error)
	CreateShowSeat(ctx context.Context, arg CreateShowSeatParams) (ShowSeat, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllCity(ctx context.Context) ([]City, error)
	GetBooking(ctx context.Context, id int64) (Booking, error)
	GetBookingByUserID(ctx context.Context, arg GetBookingByUserIDParams) ([]Booking, error)
	GetCinemaHallList(ctx context.Context, arg GetCinemaHallListParams) ([]CinemaHall, error)
	GetCinemaList(ctx context.Context, arg GetCinemaListParams) ([]Cinema, error)
	GetCinemaSeatByHallID(ctx context.Context, cinemaHallID int64) ([]CinemaSeat, error)
	GetCities(ctx context.Context, arg GetCitiesParams) ([]City, error)
	GetMovie(ctx context.Context, id int64) (Movie, error)
	GetMovies(ctx context.Context, arg GetMoviesParams) ([]Movie, error)
	GetMoviesByStatus(ctx context.Context, arg GetMoviesByStatusParams) ([]Movie, error)
	GetShow(ctx context.Context, id int64) (Show, error)
	GetShowList(ctx context.Context, arg GetShowListParams) ([]Show, error)
	GetShowSeat(ctx context.Context, id int64) (Show, error)
	GetUser(ctx context.Context, id int64) (User, error)
	UpdateCinemaSeat(ctx context.Context, arg UpdateCinemaSeatParams) (CinemaSeat, error)
	UpdateMoive(ctx context.Context, arg UpdateMoiveParams) (Movie, error)
	UpdateOauths(ctx context.Context, arg UpdateOauthsParams) (Oauth, error)
	UpdateShow(ctx context.Context, arg UpdateShowParams) (Show, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
